# config.toml
theme         = "abridge"
compile_sass  = true
minify_html   = true
base_url      = "https://www.it-help.tech"
title         = "IT Help San Diego Inc."
description   = "Expert Apple IT support in San Diego for homes and businesses. No monthly retainers!"
generate_sitemap = true

[[taxonomies]]
name = "categories"
feed = true

[[taxonomies]]
name = "tags"
feed = true

[extra]
#abridgeMode = "switcher"
js_switcher = false
js_switcher_default = "dark"
# enable non-blocking stylesheet loading
js_prestyle = false
logo = { file = "logo.svg", height = "48", width = "356", alt = "IT Help San Diego" }
stylesheets = ["css/abridge.css"]
author_name = "Carey Balboa"
copyright = false
footer_credit = false
default_og_image      = "/images/logo-slogan.jpeg"
default_twitter_image = "/images/logo-slogan.jpeg"

[[extra.menu]]
name   = "Home"
url    = "/"
slash  = true
weight = 1

[[extra.menu]]
name   = "Services"
url    = "/services/"
slash  = true
weight = 2

[[extra.menu]]
name   = "Pricing"
url    = "/billing/"
slash  = true
weight = 3

[[extra.menu]]
name   = "DNS Tool"
url    = "/dns-tool/"
slash  = true
weight = 4

[[extra.menu]]
name   = "Blog"
url    = "/blog/"
slash  = true
weight = 5

[[extra.menu]]
name   = "Our Expertise"
url    = "/about/"
slash  = true
weight = 6

[[extra.menu]]
name   = "Schedule"
url    = "https://schedule.it-help.tech/"
weight = 99
blank  = true
slash  = false
